let text = @buf-alloc 5 in
let _ = @buf-set text 0 98 in
let _ = @buf-set text 1 97 in
let _ = @buf-set text 2 97 in
let _ = @buf-set text 3 98 in
let _ = @buf-set text 4 97 in
let rows = @i64-alloc 8 in
let _ = @i64-set rows 0 0 in
let _ = @i64-set rows 1 2 in
let _ = @i64-set rows 2 2 in
let _ = @i64-set rows 3 2 in
let _ = @i64-set rows 4 4 in
let _ = @i64-set rows 5 1 in
let _ = @i64-set rows 6 2 in
let _ = @i64-set rows 7 3 in
let _ = @sort-ranges-by-bytes text rows 4 in
let ok0 = @add (@eq (@range-start rows 0) 4) (@eq (@range-len rows 0) 1) in
let ok1 = @add (@eq (@range-start rows 1) 2) (@eq (@range-len rows 1) 2) in
let ok2 = @add (@eq (@range-start rows 2) 2) (@eq (@range-len rows 2) 3) in
let ok3 = @add (@eq (@range-start rows 3) 0) (@eq (@range-len rows 3) 2) in
@add (@add ok0 ok1) (@add ok2 ok3)
