//! build.rs for the Phase 6 Stage 11 embedding demo host.
//!
//! Loads the Tacit kernel package next door, runs Stage 10 + Stage 11 to emit
//! `interface.json`, `tacit_host.h`, `tacit_host.rs`, and the LLVM object, then
//! assembles the object into a static library that the host main.rs links
//! against. The bindings are written to `$OUT_DIR/tacit_host.rs` so main.rs
//! can `include!` them with stable per-build hashes.

use std::path::{Path, PathBuf};
use std::process::Command;

use tacit_codegen::compile_library_to_object;
use tacit_typecheck::{
    emit_c_header, emit_rust_bindings, generate_host_interface, load_package, package_library,
    HostTarget,
};

fn main() {
    let kernel_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("host dir has parent")
        .join("kernel");
    rerun_if_kernel_changes(&kernel_dir);

    let package = load_package(&kernel_dir).unwrap_or_else(|diags| {
        for diag in diags {
            eprintln!("error[{}]: {}", diag.kind, diag.message);
        }
        panic!("failed to load kernel package");
    });

    let interface = generate_host_interface(&package, HostTarget::Native)
        .unwrap_or_else(|diags| panic_with_diags("interface", diags));
    let (_, library) = package_library(&package, HostTarget::Native)
        .unwrap_or_else(|diags| panic_with_diags("library spec", diags));

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set"));
    std::fs::create_dir_all(&out_dir).expect("create OUT_DIR");

    // emit_rust_bindings emits `#![allow(...)]` at the file head, which only
    // makes sense when the file is a standalone .rs unit. The host brings the
    // file in via `include!`, so strip those inner attrs (and the stray
    // `use core::ffi::c_void` they precede, which we add ourselves through
    // the `c_void as DemoUser` alias in main.rs).
    let rust_bindings = emit_rust_bindings(&interface)
        .unwrap_or_else(|diags| panic_with_diags("rust bindings", diags));
    let mut bindings_src = String::new();
    for line in rust_bindings.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("#![allow") || trimmed.starts_with("#![warn") {
            continue;
        }
        bindings_src.push_str(line);
        bindings_src.push('\n');
    }
    let bindings_path = out_dir.join("tacit_host.rs");
    std::fs::write(&bindings_path, bindings_src).expect("write bindings");
    let header_path = out_dir.join("tacit_host.h");
    std::fs::write(&header_path, emit_c_header(&interface)).expect("write header");

    let lib_module = format!("tacit_demo_kernel_{}", &library.package_hash[..12]);
    let obj_path = out_dir.join(format!("{lib_module}.o"));
    compile_library_to_object(&library, &lib_module, &obj_path).expect("emit library object");

    let archive_name = format!("{}_kernel", library.package_prefix);
    let archive_path = out_dir.join(format!("lib{archive_name}.a"));
    let _ = std::fs::remove_file(&archive_path);
    let ar = pick_archiver().expect("no archiver (ar/llvm-ar) on PATH");
    let status = Command::new(&ar)
        .arg("rcs")
        .arg(&archive_path)
        .arg(&obj_path)
        .status()
        .expect("invoke archiver");
    assert!(status.success(), "archiver {ar} failed: {status}");

    let shim_path = out_dir.join("tacit_host_shim.rs");
    let pkg = &library.package_prefix;
    let decode_op = symbol_for(&library, "decode-op", &package);
    let step_cpu = symbol_for(&library, "step-cpu", &package);
    let log_acc = symbol_for(&library, "log-acc", &package);
    let log_byte_cb = library
        .imports
        .first()
        .map(|i| i.callback.clone())
        .unwrap_or_default();
    let mut empty_callbacks_fields = String::new();
    for import in &library.imports {
        empty_callbacks_fields.push_str(&format!("        {}: None,\n", import.callback));
    }
    std::fs::write(
        &shim_path,
        format!(
            "// Auto-generated by build.rs.\n\
             pub const PACKAGE_HASH: &str = \"{pkg_hash}\";\n\
             pub const PACKAGE_PREFIX: &str = \"{prefix}\";\n\
             pub type DemoContext = super::bindings::{pkg}_context;\n\
             pub type DemoCallbacks = super::bindings::{pkg}_callbacks;\n\
             pub use super::bindings::tacit_status;\n\
             \n\
             pub use super::bindings::{decode_op} as decode_op;\n\
             pub use super::bindings::{step_cpu} as step_cpu;\n\
             pub use super::bindings::{log_acc} as log_acc;\n\
             \n\
             pub fn make_callbacks() -> DemoCallbacks {{\n\
             \x20   DemoCallbacks {{\n\
             {empty}\
             \x20   }}\n\
             }}\n\
             \n\
             pub fn install_log_callback(\n\
             \x20   callbacks: &mut DemoCallbacks,\n\
             \x20   cb: unsafe extern \"C\" fn(\n\
             \x20       *mut core::ffi::c_void, i64, *mut i64,\n\
             \x20   ) -> tacit_status,\n\
             ) {{\n\
             \x20   callbacks.{log_byte_cb} = Some(cb);\n\
             }}\n",
            pkg_hash = library.package_hash,
            prefix = library.package_prefix,
            empty = empty_callbacks_fields,
        ),
    )
    .expect("write tacit_host_shim.rs");

    println!("cargo:rustc-link-search=native={}", out_dir.display());
    println!("cargo:rustc-link-lib=static={archive_name}");
}

fn symbol_for(
    library: &tacit_typecheck::PackageLibrary,
    alias: &str,
    package: &tacit_typecheck::PackageGraph,
) -> String {
    // Manifest [exports] strips the blake3: prefix; library exports store
    // the raw hex too.
    let hash = package
        .manifest
        .exports
        .get(alias)
        .unwrap_or_else(|| panic!("manifest missing export alias {alias}"));
    library
        .exports
        .iter()
        .find(|export| &export.hash == hash)
        .unwrap_or_else(|| panic!("library missing export for alias {alias}"))
        .symbol
        .clone()
}

fn pick_archiver() -> Option<String> {
    for cand in ["ar", "llvm-ar"] {
        let status = Command::new("sh")
            .arg("-c")
            .arg(format!("command -v {cand} >/dev/null 2>&1"))
            .status();
        if matches!(status, Ok(status) if status.success()) {
            return Some(cand.to_string());
        }
    }
    None
}

fn panic_with_diags(stage: &str, diags: Vec<tacit_typecheck::Diagnostic>) -> ! {
    for diag in &diags {
        eprintln!("error[{}]: {}", diag.kind, diag.message);
    }
    panic!("kernel {stage} failed with {} diagnostics", diags.len());
}

fn rerun_if_kernel_changes(kernel_dir: &Path) {
    println!("cargo:rerun-if-changed=build.rs");
    println!(
        "cargo:rerun-if-changed={}",
        kernel_dir.join("tacit.toml").display()
    );
    let src = kernel_dir.join("src");
    if let Ok(entries) = std::fs::read_dir(&src) {
        for entry in entries.flatten() {
            println!("cargo:rerun-if-changed={}", entry.path().display());
        }
    }
}
