//! Phase 6 Stage 11 embedding demo host.
//!
//! Links a Tacit kernel that exports three scalar-typed entry points plus a
//! host import. The host:
//!   * Owns platform-shaped state (here: a Vec<i64> log).
//!   * Implements the `demo.log/write-byte` callback (records each byte the
//!     kernel hands to `log-acc`).
//!   * Calls every public export and prints a transcript.
//!
//! Hash-derived symbol and type names are generated by `build.rs` into a
//! small shim module so this file doesn't depend on any particular kernel
//! revision.

use std::cell::RefCell;
use std::ptr;

#[allow(non_camel_case_types, non_snake_case, dead_code)]
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/tacit_host.rs"));
}

#[allow(dead_code, non_camel_case_types)]
mod shim {
    include!(concat!(env!("OUT_DIR"), "/tacit_host_shim.rs"));
}

use core::ffi::c_void as DemoUser;
use shim::{decode_op, log_acc, step_cpu, tacit_status, DemoContext, PACKAGE_HASH, PACKAGE_PREFIX};

thread_local! {
    static HOST_LOG: RefCell<Vec<i64>> = const { RefCell::new(Vec::new()) };
}

unsafe extern "C" fn host_log_byte(_user: *mut DemoUser, byte: i64, out: *mut i64) -> tacit_status {
    HOST_LOG.with(|log| log.borrow_mut().push(byte));
    if !out.is_null() {
        unsafe { *out = byte };
    }
    tacit_status::TACIT_STATUS_OK
}

fn call_export_1(
    ctx: *mut DemoContext,
    sym: unsafe extern "C" fn(*mut DemoContext, i64, *mut i64) -> tacit_status,
    arg: i64,
) -> i64 {
    let mut out: i64 = 0;
    let status = unsafe { sym(ctx, arg, &mut out) };
    assert_eq!(
        status,
        tacit_status::TACIT_STATUS_OK,
        "export returned {status:?}"
    );
    out
}

fn call_export_3(
    ctx: *mut DemoContext,
    sym: unsafe extern "C" fn(*mut DemoContext, i64, i64, i64, *mut i64) -> tacit_status,
    a: i64,
    b: i64,
    c: i64,
) -> i64 {
    let mut out: i64 = 0;
    let status = unsafe { sym(ctx, a, b, c, &mut out) };
    assert_eq!(
        status,
        tacit_status::TACIT_STATUS_OK,
        "export returned {status:?}"
    );
    out
}

fn main() {
    println!("tacit embedding demo (Phase 6 Stage 11)");
    println!("  package hash: blake3:{PACKAGE_HASH}");
    println!("  symbol prefix: {PACKAGE_PREFIX}");

    let mut callbacks = shim::make_callbacks();
    shim::install_log_callback(&mut callbacks, host_log_byte);
    let mut ctx = DemoContext {
        user: ptr::null_mut(),
        callbacks: &callbacks,
    };

    // 1. Pure: decode an instruction byte's low nibble.
    let decoded = call_export_1(&mut ctx, decode_op, 0xAB);
    assert_eq!(decoded, 0x0B);
    println!("decode_op(0xAB) = {decoded}");

    // 2. Pure: step the CPU through a small program.
    //    acc = LOAD 42, then ADD 5, then ADD 3, then SUB 10.
    let mut acc: i64 = 0;
    acc = call_export_3(&mut ctx, step_cpu, acc, 8, 42); // LOAD 42
    acc = call_export_3(&mut ctx, step_cpu, acc, 1, 5); //  ADD  5
    acc = call_export_3(&mut ctx, step_cpu, acc, 1, 3); //  ADD  3
    acc = call_export_3(&mut ctx, step_cpu, acc, 2, 10); // SUB 10
    println!("cpu program ran to acc = {acc}");
    assert_eq!(acc, 40);

    // 3. Effectful: log the accumulator through the host import.
    let logged = call_export_1(&mut ctx, log_acc, acc);
    println!("log_acc({acc}) -> {logged}");

    // 4. Demonstrate that the host owns the platform state. The kernel
    //    surfaced the byte through its host import; the host accumulated
    //    it in our Vec.
    HOST_LOG.with(|log| {
        let log = log.borrow();
        println!("host_log: {:?}", *log);
        assert_eq!(*log, vec![acc]);
    });

    println!("ok");
}
